### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by Morphexe**

### CODE REVIEW

**Comment by IanMayo** [comment]
- [ ] Could you switch the logic so that the demo button goes to the app, and the login doesn't?
- [ ] Oh, and could you include the "Fork me in Gihub" banner?

**Comment by Morphexe** [comment]
@IanMayo  Both implemented.

**Comment by IanMayo** [comment]
When I go "back" from the analysis page, it keeps the bottom half of the analysis page.

**Comment by IanMayo** [comment]
selection_048

**Pull request merged**
